#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAwYami0eYqVNlFS5x1E0sIn7YcpW6SILfRguYwh6C5CBYBntz
    5UX+zVvlDs6ca/PrzAgTMd7bm51wiNMOsxy8w/B7a/RjzHfOMrCiflWv6e7k4Gwk
    qz7zU69iY+Kn6rVa13kC4mrrZCeJiObWtNjQC8YgxigfH2pTqijoKyPaGEoxUm8h
    JyjGo4syvMdn5nwk92GSPFIkPNdR3UM4Mr9yGCCAc/Zi8oaJ7C9wSHcgqZcQd0jR
    FgvvtnZi9kdwWR/Uc+d6LYGEpVHf9A87GvAaEt+4+dT/KYenr/KLkyGLRyLJmaYE
    n09AgkUGbCcrvWcM6dg8+nmWq8ryYba6qmFnBwIDAQABAoIBAA/qkRv3YXjboP6i
    +T2qsyyLHiYeZlm8WbybC487jyxP9K1jzd5XaWNeYXJcT8UZJJV9PIbne0xLIIxA
    P38/p869ooj4apTQbacBm/uj9Hna6fwDKOjknoKNdBwe8gx9qeD61N/mR0HPdqJJ
    yfLJuiKdwuhJOHYO+p6OCroxkqhYnQ5AV2KQCJuKGwskm1yEHAgaOMCSB53Qkev8
    Ulyq/LvUbKbaVf6b/lDxxAvLietwrQWiD54OXt4tSbWknlcyWG7T4t8JgaeBiO3T
    B9kf8cQ8enkpFc6vCBBnBWDq4SBPO45KSbg+a8fvCwqShtX76uP/rfa3sluqhP/H
    NEvSGAECgYEA7qnOGK3zjYZaKjdaQ1yErcnvaBiEvUjk5M/uWatjR+r2YW1f0Crn
    z1EAxSUUqrRH/xhJrUxMxp+3kASB8H3uHmWFvPnpu0iTL7w0Lo6NOv0Pqtq2GUq2
    exq2V8u2baiUjhDuU5JojGPsFhhRPlJgCd8KYlkfCopxSkUnWFE5JQcCgYEAz5V4
    NFD1nmT4fHIQmQoKDsXMjiChaZ67P7cRgRsZ/BEuqGqpV12cZ7rPcNWzsP74OXFH
    Rfqq4jMj5kc/X5Fy5HNvz97wMKoCxqqbOxYh809FPXGwSGMBG+Q3RezVH47FJMJK
    EmQAQUIGWHSgwr40F0d54k5AwPmyiVIHu+A3LgECgYBGgoBTJkFIVKMaydOvBwxj
    078ZP/Unfvuw5gWDFHF2c+Jqkke2Vpa51zKlC/l5HV4P7XsG6f3cyJ8Qu2QwSuQo
    stG6LRNys1RYy/+WqaLsBIu2bHtUKZCT+iZY9eRlrWKGPlZK9nxQzcyYEoMeKHQb
    Nnv45l+XW6Nwz9F59DUvzQKBgCWsZNJp1wnWHVrIgMalkcm4kDVDKsg2bJlVqjGa
    L48VtzgNk4otjRMuTjOWNTRsMbSLIHpM0fKXgW5rg87eYNGhOauqNEFAuZxAnkeM
    7sBvpItQNMQOY8ciFf30y4Ecsh7HvBW2XG17hBdNo1d0mZOX/0DZHttm9cYCQzEP
    sjQBAoGAGtiUuld/Q+/ybyJxRlEdNy395gjg2+xy5OHurs6jqFOvlNM5EYmFDVGK
    JWfvPXdpobWmEjVCvkAfrYfqTv8B40XwSivM5D02r9zWymTkXDEcINhl2jqGka4D
    V6cAhU/3+KRfj0ztto4kbzW3zf3p0QjQCScwvXQw/7jecnPv6gY=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/memocom_org_release.key
      iv_filename:  /etc/rails/keys/memocom_org_release.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA7R60KPc3PRkN/ViyzDcE9pGQwr/RgtR9tlva/SQ6ylBILkXj
    kZCXy5Tw7Mo2k8DTNfpv8zemnPfiHs2yMeBuNcTbu+GK5ciEwqiqpCJIdSYFrZPJ
    xMcNn3w7Zk6Oj5FiLlgGYa8yHz1BlHKwFJjFUGaglw/7sxV/vm/vwEI/IuQaVsbo
    LjGR+WvVEldA7IW9j3ovz1B46M9nJOhZsd4GjYBFN5UPKDnb79Hv9m12uL5MvJET
    85Tdp7jtIogMYG55Bmyf00LPcNCVqKHhp97KHzx+ITTgiCS1crQEwkjfcEqTr69Q
    8h8guyIBv4oW5e5O1Y9YEWeWsptkUEE4QMbxlwIDAQABAoIBAQDDzCqv+RMf3GR0
    4p0hi/0JLUH/zizOf3Ae+NJnXVc+X/R6YTN8q4zsilw26vMOJpdBZz6x8y4dR4Ls
    NKYEEXJv69IV3jO3clBN/MCLL9PtCCyAHBzr5AIXw5m47P1DB6Wu5vi+CNC2gvp3
    /gvvtgaYUWYh1wzb39DQC9ZJR2qi/2ir3RgkF5rMi9VMLOeLSQ/hTgSjHT20Y3Rg
    pkyTy316XCH2HTNblVR0xcEU3zzJWy937g0FrMfoxa18thOenHKZL2LQN4J9t/xA
    HdZSK9qPWEQsTdQGnWwC4DxdJvoMtCSgy5dFolsUdudC+2hKFOcwiuT59ELuWTJa
    b6g7IwcBAoGBAP8r29z2hWfyKxVVfqMrHRI/WcuSK3S+PaviARpGkrn1UF2qRlBE
    RTW7C3vU31B8SWJ4jW5mhX9RJEyD9Xvq8jlGWWPkDR90QQMN1OlCMRIfbc3Ch4/j
    9nYW79EcEdH8RMA6XBiX9hloJ9hQGoNnsAEne8+HhuVvHxo4eRSL2Yg3AoGBAO3j
    1mshCunX1w8iu38BfvHYHLr5L4iAUdib/u7DJm64udPmZdfFA7E6WMpAxoyHAsC8
    QiSAizn7KMwhI3hF4GFUZdR87Uch2FHVR5gjqtH25oiJIRSF5en6xPsts7KW+xc7
    zNo6D3E4D26Msi+m5tt+8ytEOAPFgAhgn4na6HGhAoGAJ7DYyCwIYDzI+s6LnjHM
    mdQE0adw3v3gdeX3qfCkTgycbZVYzo9v/IWVqbNY8RoECC8cQLnttfoXHVfBTX8k
    IkiRCvqkF+prWmBCZ+4F1/3PhJvnnjglVAUJVIt7MiB9STFKtgCdJSKQYBNFrH7q
    X6OWnJdGIlYAjoGOQ+Xk9k0CgYBLH6AexJiFsDuh8/3x5a8JAI5SHU79dEhkdx7S
    l54TaRKF8ERJF1ZLKXnQpRQOXLRp2QmqLU3KSZ5gmDZzTN3G3rgpmin0RKPjc87g
    JKNVGvtCMsvXh1FLyn1aNNyCkVtJwwC2CY/G2UVGS/gZREOzHSv9hdWKm1wLSTgY
    eKDfAQKBgQDZdaUJTncqRjSOjTd50oH+YC1jo4zrCTXDzODYBH5P+8hl+gAVNqt1
    P8sOS75g/1H/oMoBjsxrKRaV/w3siRkef4Lz5GhewiAcVuyKSO+h3eICyRUjOcWf
    JLpOyGugBq2OPNF/aygJaUOLAx2OHlGTjxo6ZpoUeFsyKuxzKvqAkA==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/memocom_org_production.key
      iv_filename:  /etc/rails/keys/memocom_org_production.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1
